### ISSUE TITLE
Hotkey support

### ISSUE THREAD

**Issue by williamcpierce** [williamcpierce/Overview#23]
https://www.reddit.com/r/Eve/comments/1g3ciqz/comment/lruy6tl/
https://discord.com/channels/1295309622445473865/1295309623074750569/1315348261212520458
https://discord.com/channels/1292215822990970981/1292217015204970527/1295353361440178208

**Comment by universenz** [comment]
There's quite a few different solutions out there for global hotkey support, this one looks reliable for Swift.
https://stackoverflow.com/questions/28281653/how-to-listen-to-global-hotkeys-with-swift-in-a-macos-app
