### ISSUE TITLE
Preview windows cannot be dragged across monitors

### ISSUE THREAD

**Issue by williamcpierce** [williamcpierce/Overview#29]
Apple M2 Max
macOS 14.7 (23H124)

**Comment by ventris** [comment]
Same problem on M3 as well.

Apple M3 Pro
macOS 15.1 (24B83)

**Comment by ventris** [comment]
Temporary fix to solve the issue of not having overview on another monitor:

Rightclick Overview in the options Dock and select it to use Monitor 2 or the one that EVE is not in. When you create a new window in Overview now they will only be created on the 2nd monitor. (They will still have the same issue of not being able to be dragged though.

**Comment by williamcpierce** [comment]
@ventris This should be resolved in v0.2.1-alpha, take a look when you have a chance and let me know if your issue is resolved! https://github.com/williamcpierce/Overview/releases/tag/v0.2.1-alpha
