### ISSUE TITLE
Feature Request: Color code windows and/or add character name

### ISSUE THREAD

**Issue by ventris** [williamcpierce/Overview#32]
- Make it possible to create a colored border around the window so that it becomes easier to differentiate between windows, e.g scouts, logi etc.

- A possibility to name windows with the characters name. If you are running eve in windowed mode the character name is already provided in the dropdown menu so it should be possible to reuse that.

**Comment by williamcpierce** [comment]
@ventris I've added borders and character names (window titles) in the latest update https://github.com/williamcpierce/Overview/releases/tag/v0.3.1-alpha

No customization options (colors etc) yet, but I've created 2 new issues for these #39 #40
